services:
  pokemon_tcg:
    build:
      context: .
      args:
        GIT_USER: ${GIT_USER}
        GIT_EMAIL: ${GIT_EMAIL}
    container_name: pokemon_tcg
    ports:
      - 8000:8000
    volumes:
      - './../:/app/'
      - '/app/docker/'
    working_dir: /app